.travis.yml, setup.py
I chose to release 1.4.6, which is the next logical version when you look at
the tags, and not 1.1, which is the next logical version when you look at the
current version on pypi.
=> release 1.4.6 to pypi

tests/test_signed_xpi.py, validator/testcases/content.py
Fixes [bug 1070188](https://bugzilla.mozilla.org/show_bug.cgi?id=1070188) (again)
=> Signature files got renamed from zigbert to mozilla (bug 1070188)

validator/loader.py, validator/main.py, validator/submain.py, validator/validate.py
This is part of a two-part fix for issues in the task queues when validator tasks fail.
The current code never cleans up its timers or signal handlers before returning, which means that the timer will fire after the timeout interval even after the `validate` function has returned. When the task completes successfully, this is relatively harmless, since it sets a flag that essentially disarms the signal handler callback. When there's an exception, the flag is not set, which means the timer fires at an arbitrary point during the execution of the task process, and raises a `ValidationTimeout` exception, likely breaking something important.
This code cleans up the timeout and signal handler after they're no longer needed, and installs a timeout by default only when launched from as a system …
=> Bug 1163799: Fix issues with the celery queues when validator tasks fail

tests/test_js_signing.py, tests/test_js_wrappedjsobject.py, tests/test_main.py, tests/test_packagelayout.py, validator/errorbundler.py, validator/testcases/chromemanifest.py, validator/testcases/javascript/actions.py, validator/testcases/javascript/call_definitions.py, validator/testcases/javascript/instanceactions.py, validator/testcases/javascript/instanceproperties.py, validator/testcases/javascript/jstypes.py, validator/testcases/javascript/predefinedentities.py, validator/testcases/markup/markuptester.py, validator/testcases/packagelayout.py, validator/testcases/regex.py
These should be all of the validator-side changes. Olympia changes will be required to display the messages, but they won't cause any trouble on the Olympia side in the mean time.
=> Bug 1183399: Add suggestions for addressing each validator message with a signing severity.

validator/testcases/javascript/predefinedentities.py
This changes:
Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using
`eval` and the `Function` constructor when at all possible.
into:
Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.
(effectively just removing the newline in the middle of the sentence)
@kmaglione r?
=> Remove newline in eval warning (no bug)

tests/test_js_instanceproperties.py, validator/testcases/javascript/entity_values.py, validator/testcases/javascript/predefinedentities.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1200822
=> Warn about NewTabURL.override (bug 1200822)

validator/testcases/installrdf.py
r? @kmaglione 
This makes the trivial signing severity messages notices instead of warnings. Since there were only these two I opted to do it here rather than in the JS on olympia.
=> Change trivial unlisted warnings to notices (bug 1172030)

validator/testcases/static_hashes.txt
This needs to be backed out as the validator not only iterates through files but also folders to find libraries (ugh).
Fixing that issue alone is not sufficient, because we probably do want the validator to recognize empty files, but they should not be part of the (html) report. They should just be greyed out in the source viewer.
r?
=> Revert "Whitelist empty file (bug 1224812)"

requirements.txt, tests/test_js_syntax.py, validator/testcases/javascript/jsshell.py
We need a version greater than 43.0a2 for [bug 1224444](https://bugzilla.mozilla.org/show_bug.cgi?id=1224444)
=> bump spidermonkey

tests/test_json_parser.py, tests/test_targetapplication.py, validator/constants.py, validator/json_parser.py, validator/validate.py
=> Use '*' as the default strict_max_version for WebExtension

validator/errorbundler.py, validator/submain.py
Note: This makes us lose the template unless we use https://github.com/blog/2111-issue-and-pull-request-templates but that would make it the default for all newly filed issues.
r?
=> Update links to point to github

validator/testcases/regex.py
'Application' that was matched in the FUEL-library removal tests
matched common strings in install.rdf and other places where it's
irrelevant and should not fail.
=> Make some JavaScript related fx47 tests exclusive for JavaScript.

tests/test_packagelayout.py, validator/testcases/packagelayout.py
=> Use correct filename(s) for binary warning

validator/testcases/javascript/call_definitions.py
We forgot to add this, so this test currently runs for every appversion, which is not what we want.
=> Add appversion to Proxy compat test

tests/test_js_signing.py, validator/testcases/javascript/predefinedentities.py
Reverting because by the time you'd see the public warning, you aren't part of the target audience for that warning anymore because after the validation ran, the add-on has already been created and subsequent submissions are just updates that aren't affected.
=> Revert Add public warning about using ctypes

validator/testcases/regex.py
@EnTeQuAk I tried to run the Fx53 compat tests today and they keep timing out. After some digging, I am fairly confident that either or both of these regex's are utterly slow and cause the validation to hit the time limit for some add-ons.
=> Fix Fx53 compat tests regex's

extras/jslibfetcher.py, validator/testcases/hashes-allowed.txt
Although this will probably be rarely used (the only scenario I could imagine are embedded webextensions), it doesn't hurt.
=> Add webextension-polyfill lib

validator/testcases/javascript/actions.py, validator/testcases/javascript/predefinedentities.py
This is readonly as defined by the standard and given that 6.x isnt in
use anymore (or, should not be) let's lift that restriction as it might
have caused mozilla/addons#397, mozilla/addons#416 and
mozilla/addons#4#397, mozilla/addons#416 and mozilla/addons#417
=> Remove 'for_appversions' restriction for readonly window.top test.

functional_tests/test_validator.py, tests/test_validate.py, validator/submain.py
Note: `test_validate_embedded_webextension_xpi` should ensure that we don't break support for embedded web extensions (I also tested this locally with a couple known embedded webextensions and a couple known webextensions) 
Supports https://github.com/mozilla/addons-server/issues/5950
=> Remove support for webextensions in amo-validator

README.md, validator/rdf.py
Fix failing unittests on python 2.7.14
The problem here is that `sax` closes any file-like object you're
passing it to and these days StringIO forces operations on closed files
to fail.
It's hard to find the actual commit that caused this change in Python
2.7.14 but explicitly reading the file and wrapping it in a new StringIO
object works.
This isn't ideal but RDF files should not be too large so that this
workaround does sound reasonable to me.
=> Fix failing unittests on Python 2.7.14

validator/testcases/javascript/jsshell.py
I'm running into crazy problems calling amo-validator via subprocess which always trace back to ``__del__`` being overwritten.
Doing it in the cleanup works perfectly fine.
=> Very simple experiment that tries to avoid overwriting __del__.

addon-validator
when addons-server is executing this in a python3 env it's defaulting to py3 which isn't working (because this package is py2 only).  So force the python to be v2.
=> force amo-validator to be executed as python2
