- tests/test_signed_xpi.py
- validator/testcases/content.py
Fixes [bug 1070188](https://bugzilla.mozilla.org/show_bug.cgi?id=1070188)
> Issue a warning when add-on is already signed. (bug 1070188)

- validator/constants.py
- validator/errorbundler.py
- validator/testcases/chromemanifest.py
- validator/testcases/content.py
- validator/testcases/javascript/call_definitions.py
- validator/testcases/javascript/entity_values.py
- validator/testcases/javascript/instanceactions.py
- validator/testcases/javascript/instanceproperties.py
- validator/testcases/javascript/jstypes.py
- validator/testcases/javascript/predefinedentities.py
- validator/testcases/javascript/traverser.py
- validator/testcases/l10ncompleteness.py
- validator/testcases/markup/csstester.py
- validator/testcases/markup/markuptester.py
- validator/testcases/packagelayout.py
> Bug 1000550 - Make warnings less stern, where applicable

- tests/test_jetpack.py
- tests/test_js_functions.py
- tests/test_js_instanceactions.py
- tests/test_js_wrappedjsobject.py
- tests/test_js_xpcom.py
- tests/test_regex.py
- validator/testcases/javascript/actions.py
- validator/testcases/javascript/call_definitions.py
- validator/testcases/javascript/instanceactions.py
- validator/testcases/javascript/predefinedentities.py
- validator/testcases/regex.py
See linked bugs for details, if necessary.
> A series of minor validator test changes

- tests/compat/test_gecko35.py
- validator/testcases/javascript/instanceactions.py
- validator/testcases/regex.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1122229
https://bugzilla.mozilla.org/show_bug.cgi?id=1121744
https://bugzilla.mozilla.org/show_bug.cgi?id=1121732
> Gecko 35 compat

- MANIFEST.in
Fixes [bug 1138662](https://bugzilla.mozilla.org/show_bug.cgi?id=1138662)
> Add the langpack reference XPIs to the package (bug 1138662)

- tests/compat/test_gecko37.py
- validator/testcases/javascript/instanceactions.py
- validator/testcases/regex.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1134367
https://bugzilla.mozilla.org/show_bug.cgi?id=1134362
> Gecko 37 compat

- tests/compat/test_gecko38.py
- validator/testcases/regex.py
> Gecko 38 compat

- tests/test_signed_xpi.py
- validator/testcases/content.py
Fixes [bug 1070188](https://bugzilla.mozilla.org/show_bug.cgi?id=1070188) (for the third time /o\)
> Warn about any pre-existing signature (bug 1070188)

- tests/compat/test_gecko39.py
- validator/testcases/regex.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1163203
https://bugzilla.mozilla.org/show_bug.cgi?id=1163199
https://bugzilla.mozilla.org/show_bug.cgi?id=1163197
> Gecko 39 compat tests

- tests/test_installrdf.py
- validator/testcases/installrdf.py
Code cleanup mostly pulled from the library validation PR, with a few minor changes.
> Cleanup testcases/installrdf.py

- tests/test_jetpack.py
- tests/test_js_instanceactions.py
- tests/test_regex.py
- validator/testcases/javascript/actions.py
- validator/testcases/javascript/instanceactions.py
- validator/testcases/javascript/predefinedentities.py
- validator/testcases/regex.py
This converts some often-problematic regex tests to code analysis tests.
> Convert regex tests to code tests

- tests/compat/test_gecko40.py
- validator/testcases/regex.py
> Fx 40 compat

- validator/testcases/javascript/predefinedentities.py
- validator/testcases/regex.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1192213
> Move Application FUEL test to a predefinedentity (bug 1192213)

- validator/testcases/javascript/predefinedentities.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1192213
> Set err_id for Application compat error (bug 1192213)

- tests/test_signed_xpi.py
- tox.ini
- validator/testcases/content.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1190704
> Error if sub-XPI is not Mozilla signed (bug 1190704)

- validator/testcases/javascript/traverser.py
This should fix the issue where the test code isn't getting run in #334.
> Force the Cc variable to trigger predefined entities

- tests/compat/test_gecko42.py
- validator/compat.py
- validator/testcases/content.py
- validator/testcases/javascript/actions.py
- validator/testcases/javascript/entity_values.py
- validator/testcases/javascript/instanceactions.py
- validator/testcases/javascript/predefinedentities.py
Fixes [bug 1214929](https://bugzilla.mozilla.org/show_bug.cgi?id=1214929)
Fixes [bug 1214926](https://bugzilla.mozilla.org/show_bug.cgi?id=1214926)
Fixes [bug 1214921](https://bugzilla.mozilla.org/show_bug.cgi?id=1214921)
Fixes [bug 1214912](https://bugzilla.mozilla.org/show_bug.cgi?id=1214912)
> Firefox 42 compatibility (pair prog with @cgrebs)

- tests/compat/test_gecko42.py
- validator/testcases/content.py
- validator/testcases/javascript/actions.py
- validator/testcases/javascript/entity_values.py
- validator/testcases/javascript/instanceactions.py
This is a follow-up to PR #334
> Fix compat tests TIERs, newTab.xul test should be a compat error

- README.md
- functional_tests/test_validator.py
- setup.cfg
- tox.ini
> Follow up to PR #341 integrate functional tests

- validator/main.py
- validator/validate.py
...when the executable is called from another directory.
@kumar303 r?
> Fixed path to appversions.json

- .gitmodules
- jetpack/generate_jp_whitelist.sh
> JPM bootstrap.js is now in jpm-core

- validator/testcases/static_hashes.txt
> Whitelist empty file (bug 1224812)

- README.md
See more details in http://ftp.mozilla.org/pub/firefox/nightly/latest-trunk/README.txt
> jsshell package moved to new directory

- tests/test_js_signing.py
- validator/testcases/javascript/entity_values.py
- validator/testcases/javascript/predefinedentities.py
This fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1216574
> Add signing warning if an addon registers to 'newtab-url-changed'.

- tests/test_js_signing.py
- validator/testcases/javascript/predefinedentities.py
> Flag 'xpinstall.signatures.required'

- validator/testcases/markup/markuptester.py
> More precise warning message for iframe type

- requirements.txt
- tests/resources/markup/csstester/unicode_space.css
- tests/test_markup_csstester.py
> Upgrade cssutils to 1.0.1 to fix unicode space parsing.

- validator/testcases/jetpack.py
needs testing first, please do not merge just yet. /cc @mstriemer
> Ignore cfx compat test during bulk validation

- validator/testcases/jetpack.py
Followup of #403.
@mstriemer r?
> Add comment to cfx compat test

- validator/errorbundler.py
- validator/submain.py
@andymckay r? (Thanks again for pointing me to that!)
> Change github issue report links to use template

- requirements.txt
> Update simplejson version to 3.8.1

- tests/compat/test_gecko40.py
- tests/compat/test_gecko47.py
- validator/testcases/javascript/entity_values.py
- validator/testcases/javascript/predefinedentities.py
- validator/testcases/regex.py
> Fix Fx47 compat tests

- validator/testcases/regex.py
> Add warning for usage of dangerous domain

- tests/test_validate.py
- validator/testcases/installrdf.py
> Fill manifest properties in bulk validation

- tests/compat/test_gecko51.py
- validator/compat.py
- validator/testcases/javascript/entity_values.py
- validator/testcases/javascript/predefinedentities.py
- validator/testcases/regex.py
> Fx51 compat tests

- tests/test_js_signing.py
- validator/testcases/javascript/predefinedentities.py
> Add public warning about using ctypes

- tests/compat/test_gecko53.py
- validator/testcases/javascript/entity_values.py
- validator/testcases/javascript/predefinedentities.py
> [fx53] Show compatibility error if an add-on uses `findTokenByName("")`

- tests/test_js_signing.py
- validator/testcases/javascript/actions.py
- validator/testcases/javascript/jstypes.py
- validator/testcases/javascript/predefinedentities.py
- validator/testcases/javascript/traverser.py
Fixes https://github.com/mozilla/addons/issues/321
> Disallow ctypes

- tests/test_js_signing.py
- validator/testcases/javascript/actions.py
- validator/testcases/javascript/jstypes.py
- validator/testcases/javascript/predefinedentities.py
- validator/testcases/javascript/traverser.py
This reverts commit 1626bee, reversing
changes made to a063002.
> Revert "Merge pull request #522 from wagnerand/ctypes_error"

- tests/test_targetapplication.py
- validator/testcases/targetapplication.py
https://github.com/mozilla/addons-server/issues/5172
> Make duplicate targetApplication entries in install.rdf an error
